pub mod alias_tests;
pub mod array_tests;
pub mod attributes_tests;
pub mod bits_tests;
pub mod canonical_names_tests;
pub mod cli_tests;
pub mod compare_generation_tests;
pub mod consts_tests;
pub mod declaration_order_tests;
pub mod direct_dependencies_tests;
pub mod enums_tests;
pub mod errcat;
pub mod errcat_docs_tests;
pub mod errcat_good_tests;
pub mod errors_tests;
pub mod experimental_flags_tests;
pub mod flat_ast_tests;
pub mod flexible_tests;
pub mod generated_name_tests;
pub mod handle_tests;
pub mod library_tests;
pub mod method_tests;
pub mod new_type_tests;
pub mod ordinals_tests;
pub mod overlay_tests;
pub mod parsing_tests;
pub mod protocol_tests;
pub mod recoverable_compilation_tests;
pub mod recoverable_parsing_tests;
pub mod reporter_tests;
pub mod resource_tests;
pub mod resourceness_tests;
pub mod sdk_fidl;
pub mod service_tests;
pub mod span_tests;
pub mod strictness_tests;
pub mod string_array_tests;
pub mod structs_tests;
pub mod table_tests;
pub mod test_library;
pub mod types_tests;
pub mod typeshape_tests;
pub mod union_tests;
pub mod using_tests;
mod utils_tests;
mod versioning_attribute_tests;
mod versioning_basic_tests;
mod versioning_decomposition_tests;
mod versioning_inheritance_tests;
mod versioning_interleaving_tests;
mod versioning_overlap_tests;
mod versioning_platform_tests;
mod versioning_replacement_tests;
mod versioning_types_tests;
